USE [master]
GO

/****** Object:  Database [vp_project]    Script Date: 7/5/2023 12:01:14 AM ******/
CREATE DATABASE [vp_project]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'vp_project', FILENAME = N'F:\SQL\New folder (2)\MSSQL16.MSSQLSERVER\MSSQL\DATA\vp_project.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'vp_project_log', FILENAME = N'F:\SQL\New folder (2)\MSSQL16.MSSQLSERVER\MSSQL\DATA\vp_project_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [vp_project].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [vp_project] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [vp_project] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [vp_project] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [vp_project] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [vp_project] SET ARITHABORT OFF 
GO

ALTER DATABASE [vp_project] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [vp_project] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [vp_project] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [vp_project] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [vp_project] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [vp_project] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [vp_project] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [vp_project] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [vp_project] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [vp_project] SET  ENABLE_BROKER 
GO

ALTER DATABASE [vp_project] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [vp_project] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [vp_project] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [vp_project] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [vp_project] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [vp_project] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [vp_project] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [vp_project] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [vp_project] SET  MULTI_USER 
GO

ALTER DATABASE [vp_project] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [vp_project] SET DB_CHAINING OFF 
GO

ALTER DATABASE [vp_project] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [vp_project] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [vp_project] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [vp_project] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [vp_project] SET QUERY_STORE = ON
GO

ALTER DATABASE [vp_project] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [vp_project] SET  READ_WRITE 
GO

